<%@ Page Language="C#" EnableSessionState="True" AutoEventWireup="true" CodeBehind="ViewCoursesRegistered.aspx.cs" Inherits="WebApplication1.ViewCoursesRegistered" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <asp:Label ID="lblMessage" runat="server" ></asp:Label>
        </div>
        <asp:GridView ID="GridView1" runat="server" DataKeyNames="COURSE_CD"
            OnRowDataBound="GridView1_RowDataBound" OnRowDeleting="GridView1_RowDeleting"
            AutoGenerateDeleteButton="true" EmptyDataText="Not Registered to any Courses yet">
            
        </asp:GridView>
        <asp:Label ID="lblSuccess" runat="server" ForeColor="DarkGreen" Font-Bold="true" ></asp:Label>
        <br />
        <br />
        <asp:Button ID="Button1" runat="server" OnClick="Button1_Click" Text="Back" />
        <br />
    </form>
</body>
</html>
